"""add template_id to routine_items

Revision ID: 637e599af6d0
Revises: 5d710fef83d4
Create Date: 2026-09-13 12:09:05.546513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '637e599af6d0'
down_revision: Union[str, Sequence[str], None] = '5d710fef83d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routine_items', sa.Column('template_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'routine_items', 'routine_items', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routine_items', type_='foreignkey')
    op.drop_column('routine_items', 'template_id')
    # ### end Alembic commands ###
