"""add status comments and alarm fields

Revision ID: 7a76f337b554
Revises: 637e599af6d0
Create Date: 2026-09-19 17:06:16.234784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a76f337b554'
down_revision: Union[str, Sequence[str], None] = '637e599af6d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE routinestatus ADD VALUE IF NOT EXISTS 'in_progress'")
    op.execute("ALTER TYPE routinestatus ADD VALUE IF NOT EXISTS 'postponed'")
    op.add_column('planning_items', sa.Column('comments', sa.String(), nullable=True))
    op.add_column('planning_items', sa.Column('alarm_lead_minutes', sa.Integer(), nullable=True))
    op.add_column('routine_items', sa.Column('comments', sa.String(), nullable=True))
    op.add_column('routine_items', sa.Column('alarm_lead_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Postgres doesn't support removing enum values easily.
    # Rolling back this migration will NOT remove 'in_progress'/'postponed' from the enum type.
    op.drop_column('routine_items', 'alarm_lead_minutes')
    op.drop_column('routine_items', 'comments')
    op.drop_column('planning_items', 'alarm_lead_minutes')
    op.drop_column('planning_items', 'comments')
    # ### end Alembic commands ###
